mysql:
  use-mysql: false
  host: 'your-host'
  port: 3306
  database: 'your-database'
  username: 'your-username'
  password: 'your-password'

use-actionbar: false

mongo-uri: ''
mong-database: ''
mong-collection: ''

locations:
  lobbyspawn: