name: Items
version: 1.0
main: net.maploop.items.Items
authors: [ Maploop ]
description: ITEMS
website: POG.com
commands:
  item:
  items:
    aliases:
      - e
  undozap:
  undograndarchitect:
  mcitems:
  gamemode:
    aliases:
      - gm
  sbclear:
    aliases:
      - cl
      - clear
  loop:
  createitem:
  itemslobbyset: