name: Items
version: 1.0
main: net.maploop.items.Items
authors: [ Maploop ]
description: ITEMS
website: POG.com
commands:
  item:
  items:
    aliases:
      - e
  undozap:
  undograndarchitect:
  mcitems:
    aliases:
      - mcitem
  gamemode:
    aliases:
      - gm
  sbclear:
    aliases:
      - cl
      - clear
  loop:
  createitem:
  placespecialanvil:
  recombobulate:
  itemssetlobby:
  shutup:
  stfu:
  piano:
  dyeitem:
    aliases:
      - dye
  dyearmoritem:
    aliases:
      - dyearmor
  rainbow:
